import Foundation

/// Proveedor con base de datos de cientos de dominios de contenido para adultos
public struct AdultBlockListProvider {
    public static let adultDomains: [String] = [
        "pornhub.com", "www.pornhub.com", "pornhubpremium.com",
        "xvideos.com", "www.xvideos.com", "xvideos2.com", "xvideos3.com",
        "xnxx.com", "www.xnxx.com", "xnxx2.com", "xnxx3.com", "xnxx.tv",
        "xhamster.com", "www.xhamster.com", "xhamster.desi", "xhamster2.com", "xhamster3.com",
        "redtube.com", "www.redtube.com",
        "youporn.com", "www.youporn.com",
        "onlyfans.com", "www.onlyfans.com",
        "chaturbate.com", "www.chaturbate.com",
        "stripchat.com", "www.stripchat.com",
        "cam4.com", "www.cam4.com",
        "camsoda.com", "www.camsoda.com",
        "bongacams.com", "www.bongacams.com",
        "myfreecams.com", "www.myfreecams.com",
        "livejasmin.com", "www.livejasmin.com",
        "flirt4free.com", "www.flirt4free.com",
        "eporner.com", "www.eporner.com",
        "tube8.com", "www.tube8.com",
        "spankbang.com", "www.spankbang.com",
        "beeg.com", "www.beeg.com",
        "hqporner.com", "www.hqporner.com",
        "tnaflix.com", "www.tnaflix.com",
        "rule34.xxx", "rule34.paheal.net",
        "nhentai.net", "www.nhentai.net",
        "hentaihaven.xxx", "hentaihaven.com",
        "fapello.com", "www.fapello.com",
        "coomer.party", "coomer.su",
        "kemono.party", "kemono.su",
        "erome.com", "www.erome.com",
        "redgifs.com", "www.redgifs.com",
        "motherless.com", "www.motherless.com",
        "brazzers.com", "www.brazzers.com",
        "bangbros.com", "www.bangbros.com",
        "realitykings.com", "www.realitykings.com",
        "naughtyamerica.com", "www.naughtyamerica.com",
        "twistys.com", "www.twistys.com",
        "mofos.com", "www.mofos.com",
        "wicked.com", "www.wicked.com",
        "digitalplayground.com", "www.digitalplayground.com",
        "evilangel.com", "www.evilangel.com",
        "babes.com", "www.babes.com",
        "kink.com", "www.kink.com",
        "porn.com", "www.porn.com",
        "fuq.com", "www.fuq.com",
        "daftsex.com", "www.daftsex.com",
        "heavy-r.com", "www.heavy-r.com",
        "pornmd.com", "www.pornmd.com",
        "porn300.com", "www.porn300.com",
        "drtuber.com", "www.drtuber.com",
        "nuvid.com", "www.nuvid.com",
        "sunporno.com", "www.sunporno.com",
        "txxx.com", "www.txxx.com",
        "upornia.com", "www.upornia.com",
        "tubepornclassic.com", "www.tubepornclassic.com",
        "vjav.com", "www.vjav.com",
        "javhd.com", "www.javhd.com",
        "javlibrary.com", "www.javlibrary.com",
        "xcafe.com", "www.xcafe.com",
        "porntrex.com", "www.porntrex.com",
        "gotporn.com", "www.gotporn.com",
        "pornone.com", "www.pornone.com",
        "hdporn92.com", "www.hdporn92.com",
        "cumlouder.com", "www.cumlouder.com",
        "slutload.com", "www.slutload.com",
        "definebabe.com", "www.definebabe.com",
        "badjojo.com", "www.badjojo.com",
        "porndig.com", "www.porndig.com",
        "pornrabbit.com", "www.pornrabbit.com",
        "pornid.xxx", "www.pornid.xxx",
        "xxxvogue.net", "www.xxxvogue.net",
        "zbporn.com", "www.zbporn.com",
        "cliphunter.com", "www.cliphunter.com",
        "sublimefap.com", "www.sublimefap.com",
        "thumbzilla.com", "www.thumbzilla.com",
        "porndoe.com", "www.porndoe.com",
        "porndude.com", "theporndude.com",
        "mangaporn.net", "www.mangaporn.net",
        "gelbooru.com", "www.gelbooru.com",
        "danbooru.donmai.us", "safebooru.org",
        "e-hentai.org", "exhentai.org",
        "hanime.tv", "www.hanime.tv",
        "hentai.tv", "www.hentai.tv",
        "fansly.com", "www.fansly.com",
        "manyvids.com", "www.manyvids.com",
        "loyalfans.com", "www.loyalfans.com",
        "clips4sale.com", "www.clips4sale.com",
        "iwantclips.com", "www.iwantclips.com",
        "modelhub.com", "www.modelhub.com",
        "fetlife.com", "www.fetlife.com",
        "adultfriendfinder.com", "www.adultfriendfinder.com",
        "ashleymadison.com", "www.ashleymadison.com",
        "escortdirectory.com", "www.escortdirectory.com",
        "backpage.com", "www.backpage.com",
        "megapersonals.eu", "www.megapersonals.eu",
        "eros.com", "www.eros.com",
        "bedpage.com", "www.bedpage.com",
        "leolist.cc", "www.leolist.cc",
        "cityxguide.com", "www.cityxguide.com",
        "skipthegames.com", "www.skipthegames.com",
        
        // Instancias alternativas de Reddit (Libreddit & Redlib - Sin filtros NSFW)
        "libreddit.org", "www.libreddit.org", "libreddit.kavin.rocks", "libreddit.spike.codes",
        "libreddit.northboot.xyz", "libreddit.de", "libreddit.hu", "libreddit.projectsegfau.lt",
        "libreddit.privacydev.net", "libreddit.freedit.eu", "libreddit.mha.fi", "libreddit.oxymagnesium.com",
        "libreddit.tinfoil-hat.net", "libreddit.daveinfinity.com", "libreddit.nohost.network",
        "lr.artemislena.eu", "lr.aeong.one", "reddit.invak.id", "snoo.habedieeh.re", "safereddit.com",
        
        "redlib.catsarch.com", "redlib.perennialte.ch", "redlib.freedit.eu", "redlib.tux.pizza",
        "redlib.ducks.party", "redlib.vslater.top", "redlib.privacydev.net", "redlib.matthew.science",
        "redlib.niruc.com", "redlib.seasi.dev", "redlib.kittywi.re", "redlib.r4fo.com",
        "redlib.tinfoil-hat.net", "redlib.nohost.network", "redlib.drunkencat.net", "redlib.private.coffee",
        "redlib.daik.in", "redlib.402.capital", "redlib.nadeko.net", "redlib.tux.pizza", "redlib.incognet.io",
        
        "teddit.net", "www.teddit.net", "teddit.rawbit.ninja", "teddit.zaggy.nl",
        "teddit.sethforprivacy.com", "teddit.pussthecat.org", "teddit.domain.glass",
        
        // Instancias alternativas de Twitter / X (Nitter - Sin filtros de contenido)
        "nitter.net", "www.nitter.net", "nitter.cz", "nitter.it", "nitter.privacydev.net",
        "nitter.projectsegfau.lt", "nitter.poast.org", "nitter.woodland.cafe", "nitter.inpt.fr",
        "nitter.eu", "nitter.d420.de", "nitter.moomoo.me", "nitter.x86-64-unknown-linux-gnu.zip",
        "nitter.kavin.rocks", "nitter.1d4.us", "nitter.uni-sonia.com", "nitter.soopy.moe",
        
        // Instancias alternativas de TikTok (ProxiTok)
        "proxitok.pabloferreiro.es", "proxitok.pussthecat.org", "tok.habedieeh.re", "proxitok.kavin.rocks"
    ]
    
    /// Patrones heurísticos para detectar instancias presentes y futuras automáticamente
    public static let adultInstanceKeywords: [String] = [
        "libreddit", "redlib", "teddit", "nitter", "proxitok",
        "coomer.party", "coomer.su", "kemono.party", "kemono.su",
        "fapello", "pornhub", "xvideos", "xnxx", "xhamster",
        "redtube", "youporn", "chaturbate", "stripchat", "erome"
    ]
}
