import Foundation

/// Proveedor con base de datos masiva de más de 1,000 dominios de contenido para adultos
/// (Globales, Latinoamericanos, Hispanos, Brasileños, Europeos, Asiáticos, Hentai, Cams y AI NSFW)
public struct AdultBlockListProvider {
    public static let adultDomains: [String] = [
        // MARK: - TeraBox & Espejos / Nubes de Filtraciones & Descargadores MP4
        "terabox.app", "www.terabox.app", "terabox.com", "www.terabox.com",
        "teraboxapp.com", "www.teraboxapp.com", "terabox.fun", "www.terabox.fun",
        "terabox.link", "www.terabox.link", "terabox.me", "www.terabox.me",
        "terabox.in", "www.terabox.in", "terabox.club", "www.terabox.club",
        "terabox.space", "www.terabox.space", "terabox.org", "www.terabox.org",
        "terabox.net", "www.terabox.net", "terabox.top", "www.terabox.top",
        "terabox.site", "www.terabox.site", "terabox.tech", "www.terabox.tech",
        "terabox.vip", "www.terabox.vip", "terabox.lat", "www.terabox.lat",
        "terabox.asia", "www.terabox.asia", "terabox.download", "www.terabox.download",
        "terabox.is", "www.terabox.is", "terabox.pw", "www.terabox.pw",
        "terabox.la", "www.terabox.la",
        "1024tera.com", "www.1024tera.com", "1024terabox.com", "www.1024terabox.com",
        "1024terabox.net", "www.1024terabox.net", "1024tera.co", "www.1024tera.co",
        "4funbox.com", "www.4funbox.com", "mirrobox.com", "www.mirrobox.com",
        "nephobox.com", "www.nephobox.com", "freeterabox.com", "www.freeterabox.com",
        "tibibox.com", "www.tibibox.com", "momerybox.com", "www.momerybox.com",
        "boxtera.com", "www.boxtera.com", "terastorage.com", "www.terastorage.com",
        "terasharelink.com", "www.terasharelink.com", "terafileshare.com", "www.terafileshare.com",
        "teraboxshare.com", "www.teraboxshare.com", "teraboxurl.com", "www.teraboxurl.com",
        "teraboxlink.com", "www.teraboxlink.com", "terashare.net", "www.terashare.net",
        "terashare.org", "www.terashare.org", "terashare.top", "www.terashare.top",
        "terafiles.net", "www.terafiles.net", "teradrive.co", "www.teradrive.co",
        "teradrop.net", "www.teradrop.net", "teraboxcdn.com", "www.teraboxcdn.com",
        "teraboxhls.com", "www.teraboxhls.com",
        // Herramientas y sitios de descarga / extracción / bypass de videos MP4 de TeraBox
        "teraboxdownloader.com", "www.teraboxdownloader.com",
        "terabox-downloader.com", "www.terabox-downloader.com",
        "teraboxdl.com", "www.teraboxdl.com", "teraboxdl.net", "www.teraboxdl.net",
        "teraboxdownloader.online", "www.teraboxdownloader.online",
        "teraboxdownloader.in", "www.teraboxdownloader.in",
        "teraboxdownloader.org", "www.teraboxdownloader.org",
        "teraboxdownloader.me", "www.teraboxdownloader.me",
        "teraboxdownloaderpro.com", "www.teraboxdownloaderpro.com",
        "teradownloader.com", "www.teradownloader.com",
        "teradownloader.org", "www.teradownloader.org",
        "teradownloader.online", "www.teradownloader.online",
        "teradownload.com", "www.teradownload.com",
        "teradownload.org", "www.teradownload.org",
        "teradl.com", "www.teradl.com", "teradl.in", "www.teradl.in",
        "teradl.org", "www.teradl.org", "tera-dl.com", "www.tera-dl.com",
        "teraboxvideodownloader.com", "www.teraboxvideodownloader.com",
        "teraboxvideo.com", "www.teraboxvideo.com",
        "teraboxdirect.com", "www.teraboxdirect.com",
        "teraboxdirectdownload.com", "www.teraboxdirectdownload.com",
        "teraboxplayer.com", "www.teraboxplayer.com",
        "teraboxplayer.online", "www.teraboxplayer.online",
        "teraboxplayer.in", "www.teraboxplayer.in",
        "flowvideoplayer.com", "www.flowvideoplayer.com",
        "teraboxlinkdownloader.com", "www.teraboxlinkdownloader.com",
        "terastream.xyz", "www.terastream.xyz",
        "teraboxstream.com", "www.teraboxstream.com",
        "teraboxbypass.com", "www.teraboxbypass.com",
        "teraboxgenerator.com", "www.teraboxgenerator.com",
        "teraboxmp4.com", "www.teraboxmp4.com",
        "teramp4.com", "www.teramp4.com",
        "terabox-download.com", "www.terabox-download.com",
        "terabox.tools", "www.terabox.tools",
        "teratool.com", "www.teratool.com",
        "teraboxapp.org", "www.teraboxapp.org",
        "terafast.com", "www.terafast.com",
        "terasaver.com", "www.terasaver.com",
        "terasaver.net", "www.terasaver.net",
        "teraget.com", "www.teraget.com",
        "teraboxbot.com", "www.teraboxbot.com",
        "teraboxlink.net", "www.teraboxlink.net",
        "teradown.in", "www.teradown.in",
        "terafiles.in", "www.terafiles.in",
        "freeteraboxdownloader.com", "www.freeteraboxdownloader.com",
        "teraboxapi.com", "www.teraboxapi.com",
        
        // MARK: - Gigantes Globales & Redes Principales
        "pornhub.com", "www.pornhub.com", "pornhubpremium.com", "pornhub.org", "pornhubselect.com",
        "xvideos.com", "www.xvideos.com", "xvideos2.com", "xvideos3.com", "xvideos.es", "xvideos.in", "xvideos-cdn.com",
        "xnxx.com", "www.xnxx.com", "xnxx2.com", "xnxx3.com", "xnxx.tv", "xnxx.es", "xnxx.in", "xnxx.gold",
        "xhamster.com", "www.xhamster.com", "xhamster.desi", "xhamster2.com", "xhamster3.com", "xhamster.xxx", "xhamster.vip", "xhwide.com",
        "redtube.com", "www.redtube.com", "redtube.net", "redtube.xxx",
        "youporn.com", "www.youporn.com", "youporn.net", "youporngay.com",
        "onlyfans.com", "www.onlyfans.com", "onlyfans.page",
        "chaturbate.com", "www.chaturbate.com", "m.chaturbate.com",
        "stripchat.com", "www.stripchat.com", "stripchat.xxx",
        "cam4.com", "www.cam4.com", "cam4.es", "cam4.com.br",
        "camsoda.com", "www.camsoda.com",
        "bongacams.com", "www.bongacams.com", "bongacams2.com", "bongacams.net",
        "myfreecams.com", "www.myfreecams.com", "mfc.com",
        "livejasmin.com", "www.livejasmin.com", "jasmin.com",
        "flirt4free.com", "www.flirt4free.com",
        "eporner.com", "www.eporner.com", "eporner.tv",
        "tube8.com", "www.tube8.com", "tube8.es",
        "spankbang.com", "www.spankbang.com", "la.spankbang.com", "es.spankbang.com", "spankbang.party",
        "beeg.com", "www.beeg.com", "beeg.porn",
        "hqporner.com", "www.hqporner.com",
        "tnaflix.com", "www.tnaflix.com",
        "fapello.com", "www.fapello.com", "fapello.su",
        "coomer.party", "coomer.su", "coomer.st",
        "kemono.party", "kemono.su", "kemono.st",
        "erome.com", "www.erome.com",
        "redgifs.com", "www.redgifs.com", "v3.redgifs.com",
        "motherless.com", "www.motherless.com",
        "brazzers.com", "www.brazzers.com", "brazzersnetwork.com",
        "bangbros.com", "www.bangbros.com", "bangbrosnetwork.com",
        "realitykings.com", "www.realitykings.com",
        "naughtyamerica.com", "www.naughtyamerica.com",
        "twistys.com", "www.twistys.com",
        "mofos.com", "www.mofos.com",
        "wicked.com", "www.wicked.com",
        "digitalplayground.com", "www.digitalplayground.com",
        "evilangel.com", "www.evilangel.com",
        "babes.com", "www.babes.com",
        "kink.com", "www.kink.com",
        "porn.com", "www.porn.com",
        "fuq.com", "www.fuq.com",
        "daftsex.com", "www.daftsex.com",
        "heavy-r.com", "www.heavy-r.com",
        "pornmd.com", "www.pornmd.com",
        "porn300.com", "www.porn300.com",
        "drtuber.com", "www.drtuber.com",
        "nuvid.com", "www.nuvid.com",
        "sunporno.com", "www.sunporno.com",
        "txxx.com", "www.txxx.com",
        "upornia.com", "www.upornia.com",
        "tubepornclassic.com", "www.tubepornclassic.com",
        "porntrex.com", "www.porntrex.com",
        "gotporn.com", "www.gotporn.com",
        "pornone.com", "www.pornone.com",
        "hdporn92.com", "www.hdporn92.com",
        "cumlouder.com", "www.cumlouder.com",
        "slutload.com", "www.slutload.com",
        "definebabe.com", "www.definebabe.com",
        "badjojo.com", "www.badjojo.com",
        "porndig.com", "www.porndig.com",
        "pornrabbit.com", "www.pornrabbit.com",
        "pornid.xxx", "www.pornid.xxx",
        "xxxvogue.net", "www.xxxvogue.net",
        "zbporn.com", "www.zbporn.com",
        "cliphunter.com", "www.cliphunter.com",
        "sublimefap.com", "www.sublimefap.com",
        "thumbzilla.com", "www.thumbzilla.com",
        "porndoe.com", "www.porndoe.com",
        "porndude.com", "theporndude.com", "es.theporndude.com", "theporndude.vip",
        "youjizz.com", "www.youjizz.com",
        "keezmovies.com", "www.keezmovies.com",
        "extremetube.com", "www.extremetube.com",
        "4tube.com", "www.4tube.com",
        "tubegalore.com", "www.tubegalore.com",
        "xtube.com", "www.xtube.com",
        "pornhat.com", "www.pornhat.com", "pornhat.one",
        "fapster.xxx", "www.fapster.xxx",
        "pornsharing.com", "www.pornsharing.com",
        "freeones.com", "www.freeones.com", "freeones.es",
        "xbabe.com", "www.xbabe.com",
        "porntube.com", "www.porntube.com",
        "pornpics.com", "www.pornpics.com",
        "imagefap.com", "www.imagefap.com",
        "fuskator.com", "www.fuskator.com",
        "scrolller.com", "www.scrolller.com",
        "bravoteens.com", "www.bravoteens.com",
        "voyeurhit.com", "www.voyeurhit.com",
        "voyeurweb.com", "www.voyeurweb.com",
        "camwhores.tv", "www.camwhores.tv", "camwhores.video", "camwhoresbay.com",
        "anonib.al", "simpcity.su", "thothub.vip", "fapcat.com", "leaks.sexy", "onlyleaks.net",

        // MARK: - Sitios Hispanos, Españoles y Latinoamericanos
        "pasion.com", "www.pasion.com", "m.pasion.com",
        // MARK: - Estudios y Portales Populares Latinos e Hispanos (SexMex, InkaSex, Milky, etc.)
        "sexmex.xxx", "www.sexmex.xxx", "sexmex.com", "www.sexmex.com", "sexmexoficial.com", "www.sexmexoficial.com", "sexmexpass.com", "www.sexmexpass.com", "sexmexhd.com", "www.sexmexhd.com", "sexmexmovies.com", "www.sexmexmovies.com", "sexmextube.com", "www.sexmextube.com", "sexmexvr.com", "www.sexmexvr.com",
        "inkasex.com", "www.inkasex.com", "inkasex.pe", "www.inkasex.pe", "inkasex.net", "www.inkasex.net", "inkasex.xxx", "www.inkasex.xxx", "inkasexvip.com", "www.inkasexvip.com", "inkasexoficial.com", "www.inkasexoficial.com", "inkasexvideos.com", "www.inkasexvideos.com",
        "milkyperu.com", "www.milkyperu.com", "milkyperu.xxx", "www.milkyperu.xxx", "milkyperu.net", "www.milkyperu.net", "milky.pe", "www.milky.pe", "milkyperuoficial.com", "www.milkyperuoficial.com", "milkyvip.com", "www.milkyvip.com",
        "privaditasperu.com", "www.privaditasperu.com", "privaditas.xxx", "www.privaditas.xxx",
        "todoxxxperu.com", "www.todoxxxperu.com", "kinesiologasperu.xxx", "www.kinesiologasperu.xxx", "scortsperu.xxx", "www.scortsperu.xxx", "peruputas.xxx", "www.peruputas.xxx",
        "solocali.com", "www.solocali.com", "bogotaputas.com", "www.bogotaputas.com", "paisitas.xxx", "www.paisitas.xxx", "pasionpaisa.com", "www.pasionpaisa.com", "scortscolombia.xxx", "www.scortscolombia.xxx",
        "scortsmexico.xxx", "www.scortsmexico.xxx", "mexicanasvip.xxx", "www.mexicanasvip.xxx", "eroticosmexico.com", "www.eroticosmexico.com",
        "scortsargentina.xxx", "www.scortsargentina.xxx", "argentinasxxx.com", "www.argentinasxxx.com",
        "scortschile.xxx", "www.scortschile.xxx", "chilenasxxx.com", "www.chilenasxxx.com",
        "latinleche.com", "www.latinleche.com", "latinosextube.com", "www.latinosextube.com",
        "rubias19.com", "www.rubias19.com", "perritasxxx.com", "www.perritasxxx.com",
        "tubecasero.com", "www.tubecasero.com", "videoscaseros.xxx", "www.videoscaseros.xxx",
        "chupameesta.com", "www.chupameesta.com", "telopongo.com", "www.telopongo.com",
        "xlatina.com", "www.xlatina.com", "latinaporns.com", "www.latinaporns.com",
        "calienteslatinas.com", "www.calienteslatinas.com", "tetaslatinas.com", "www.tetaslatinas.com", "culazoslatinos.com", "www.culazoslatinos.com",
        "pasion.com", "www.pasion.com", "m.pasion.com",
        "mileroticos.com", "www.mileroticos.com", "es.mileroticos.com", "mx.mileroticos.com", "co.mileroticos.com", "ar.mileroticos.com", "cl.mileroticos.com", "pe.mileroticos.com",
        "putalocura.com", "www.putalocura.com",
        "torbe.com", "www.torbe.com",
        "cumlouder.es", "www.cumlouder.es",
        "fototetas.es", "www.fototetas.es",
        "fototetas.com", "www.fototetas.com",
        "coger.com", "www.coger.com",
        "follar.com", "www.follar.com",
        "tetasgrandes.com", "www.tetasgrandes.com",
        "culioneros.com", "www.culioneros.com",
        "peladas.com", "www.peladas.com",
        "chongos.xxx", "www.chongos.xxx",
        "zonaperv.com", "www.zonaperv.com",
        "pornogratis.com", "www.pornogratis.com", "pornogratisdiario.com",
        "pornolatinas.com", "www.pornolatinas.com",
        "pornosmexico.com", "www.pornosmexico.com",
        "xmexicana.com", "www.xmexicana.com",
        "chilenitas.com", "www.chilenitas.com",
        "argentinaporn.com", "www.argentinaporn.com",
        "colombianas.xxx", "www.colombianas.xxx",
        "peruanitas.xxx", "www.peruanitas.xxx",
        "venezolanas.xxx", "www.venezolanas.xxx",
        "madurasporno.xxx", "www.madurasporno.xxx",
        "putasbogota.com", "www.putasbogota.com",
        "prepagoscolombia.xxx", "www.prepagoscolombia.xxx",
        "simpleescorts.es", "www.simpleescorts.es",
        "loquo.com", "www.loquo.com",
        "tablondeanuncios.com", "www.tablondeanuncios.com",
        "portalnovias.com", "www.portalnovias.com",
        "eroticos.com", "www.eroticos.com",
        "fotosdesnudas.xxx", "www.fotosdesnudas.xxx",
        "videosporno.xxx", "www.videosporno.xxx",
        "pornolatina.org", "www.pornolatina.org",
        "pornohispano.com", "www.pornohispano.com",
        "videosdecaseros.com", "www.videosdecaseros.com",
        "caserosargentinos.com", "www.caserosargentinos.com",
        "caserosmexicanos.com", "www.caserosmexicanos.com",
        "caseroscolombianos.com", "www.caseroscolombianos.com",
        "caserosperuanos.com", "www.caserosperuanos.com",
        "caseroslatinos.com", "www.caseroslatinos.com",
        "putasdebuenosaires.com", "www.putasdebuenosaires.com",
        "scorts.es", "www.scorts.es",
        "pasioncontactos.com", "www.pasioncontactos.com",
        "contactosx.es", "www.contactosx.es",
        "mundosexanuncio.com", "www.mundosexanuncio.com",
        "sexosexy.com", "www.sexosexy.com",
        "foropasion.com", "www.foropasion.com",
        "vivastreet.es", "www.vivastreet.es", "vivastreet.co", "vivastreet.com.mx",
        "clasificadosx.com", "www.clasificadosx.com",
        "locanto.es", "www.locanto.es", "locanto.com.mx", "locanto.com.co", "locanto.com.ar", "locanto.cl", "locanto.com.pe",
        "skokka.com", "www.skokka.com", "es.skokka.com", "mx.skokka.com", "co.skokka.com", "ar.skokka.com", "cl.skokka.com", "pe.skokka.com",
        "adultguia.com", "www.adultguia.com",
        "guiadeplacer.com", "www.guiadeplacer.com",
        "sexogratis.com", "www.sexogratis.com",
        "pornoes.com", "www.pornoes.com",
        "pornotube.es", "www.pornotube.es",
        "latinaporn.com", "www.latinaporn.com",
        "latinasex.com", "www.latinasex.com",
        "mexicanasex.com", "www.mexicanasex.com",
        "colombianasex.com", "www.colombianasex.com",
        "argentinasex.com", "www.argentinasex.com",
        "pornomexico.com", "www.pornomexico.com",
        "pornoargentina.com", "www.pornoargentina.com",
        "pornobogota.com", "www.pornobogota.com",
        "pornochile.com", "www.pornochile.com",
        "pornoperu.com", "www.pornoperu.com",
        "escortsmadrid.xxx", "escortsbarcelona.xxx",
        "slutsspain.com", "madurascalientes.com", "jovencitasporno.com",

        // MARK: - Sitios Brasileños y en Portugués
        "xvideos.com.br", "www.xvideos.com.br",
        "brasileirinhas.com.br", "www.brasileirinhas.com.br",
        "pornocombr.com", "www.pornocombr.com",
        "camerafap.com", "www.camerafap.com",
        "camerasex.com.br", "www.camerasex.com.br",
        "novinhas.xxx", "www.novinhas.xxx",
        "garotasdeprograma.com.br", "www.garotasdeprograma.com.br",
        "fatalmodel.com", "www.fatalmodel.com",
        "photovacom.com", "www.photovacom.com",
        "acompanhantes.com.br", "www.acompanhantes.com.br",
        "redetvporn.com", "www.redetvporn.com",
        "gostosas.com", "www.gostosas.com",
        "sexo.net", "www.sexo.net",
        "bundas.xxx", "www.bundas.xxx",
        "safadas.xxx", "www.safadas.xxx",
        "amadorbrasileiro.com", "www.amadorbrasileiro.com",
        "pornobrasil.tv", "www.pornobrasil.tv",
        "sexoamador.org", "www.sexoamador.org",
        "flagras.net", "www.flagras.net",
        "gatasdoinstagram.com", "www.gatasdoinstagram.com",

        // MARK: - JAV, Tubes Asiáticos & Anime NSFW
        "vjav.com", "www.vjav.com",
        "javhd.com", "www.javhd.com",
        "javlibrary.com", "www.javlibrary.com",
        "xcafe.com", "www.xcafe.com",
        "javfor.me", "www.javfor.me",
        "javjunkies.com", "www.javjunkies.com",
        "missav.com", "www.missav.com", "missav.ws", "missav.ai",
        "jable.tv", "www.jable.tv",
        "supjav.com", "www.supjav.com",
        "avgle.com", "www.avgle.com",
        "javseen.com", "www.javseen.com",
        "javmenu.com", "www.javmenu.com",
        "javfinder.me", "www.javfinder.me",
        "javmost.cx", "www.javmost.cx",
        "7mmtv.tv", "www.7mmtv.tv",
        "thisav.com", "www.thisav.com",
        "tktube.com", "www.tktube.com",
        "fc2.com", "adult.contents.fc2.com",
        "dmm.co.jp", "www.dmm.co.jp",
        "r18.com", "www.r18.com",
        "tokyo-hot.com", "www.tokyo-hot.com",
        "caribbeancom.com", "www.caribbeancom.com",
        "1pondo.tv", "www.1pondo.tv",
        "pacopacomama.com", "www.pacopacomama.com",
        "heyzo.com", "www.heyzo.com",

        // MARK: - Hentai, Manga NSFW & Boorus Explícitos
        "rule34.xxx", "rule34.paheal.net", "rule34video.com", "rule34.world", "rule34.us",
        "nhentai.net", "www.nhentai.net", "nhentai.to", "nhentai.xxx", "nhentai.website",
        "hentaihaven.xxx", "hentaihaven.com", "hentaihaven.me", "hentaihaven.red",
        "mangaporn.net", "www.mangaporn.net",
        "gelbooru.com", "www.gelbooru.com",
        "danbooru.donmai.us", "safebooru.org",
        "e-hentai.org", "exhentai.org",
        "hanime.tv", "www.hanime.tv",
        "hentai.tv", "www.hentai.tv",
        "hitomi.la", "www.hitomi.la",
        "tsumino.com", "www.tsumino.com",
        "pururin.io", "www.pururin.io",
        "3hentai.net", "www.3hentai.net",
        "hentai2read.com", "www.hentai2read.com",
        "hentai3z.xyz", "www.hentai3z.xyz",
        "simply-hentai.com", "www.simply-hentai.com",
        "hentaimama.io", "www.hentaimama.io",
        "doujins.com", "www.doujins.com",
        "ero-cool.com", "www.ero-cool.com",
        "hentaifox.com", "www.hentaifox.com",
        "fakku.net", "www.fakku.net",
        "asmhentai.com", "www.asmhentai.com",
        "e-shuushuu.net", "tbib.org", "yande.re",
        "sankakucomplex.com", "chan.sankakucomplex.com", "idol.sankakucomplex.com",
        "luscious.net", "www.luscious.net",
        "multporn.net", "www.multporn.net",
        "hentai-foundry.com", "www.hentai-foundry.com",
        "hentaiera.com", "www.hentaiera.com",
        "hentaicloud.com", "www.hentaicloud.com",
        "eromangaporn.com", "www.eromangaporn.com",
        "cartoonporno.xxx", "www.cartoonporno.xxx",
        "toonporn.com", "www.toonporn.com",

        // MARK: - Plataformas de Creadores Adultos & Fans
        "fansly.com", "www.fansly.com",
        "manyvids.com", "www.manyvids.com",
        "loyalfans.com", "www.loyalfans.com",
        "clips4sale.com", "www.clips4sale.com",
        "iwantclips.com", "www.iwantclips.com",
        "modelhub.com", "www.modelhub.com",
        "pocketstars.com", "www.pocketstars.com",
        "unfiltrd.com", "www.unfiltrd.com",
        "fanvue.com", "www.fanvue.com",
        "justforfans.com", "www.justforfans.com",
        "admireme.vip", "www.admireme.vip",
        "fetlife.com", "www.fetlife.com",
        "adultfriendfinder.com", "www.adultfriendfinder.com",
        "ashleymadison.com", "www.ashleymadison.com",
        "escortdirectory.com", "www.escortdirectory.com",
        "backpage.com", "www.backpage.com",
        "megapersonals.eu", "www.megapersonals.eu",
        "eros.com", "www.eros.com", "erosguide.com",
        "bedpage.com", "www.bedpage.com",
        "leolist.cc", "www.leolist.cc",
        "cityxguide.com", "www.cityxguide.com",
        "skipthegames.com", "www.skipthegames.com",
        "adultlook.com", "www.adultlook.com",
        "rubratings.com", "www.rubratings.com",
        "eurobabeindex.com", "www.eurobabeindex.com",
        "sextpanther.com", "www.sextpanther.com",
        "camster.com", "www.camster.com",
        "liveprivates.com", "www.liveprivates.com",
        "streamate.com", "www.streamate.com",
        "imlive.com", "www.imlive.com",
        "camfrog.com", "www.camfrog.com",
        "jerkmate.com", "www.jerkmate.com",
        "babestation.tv", "www.babestation.tv",
        "webcamromance.com", "www.webcamromance.com",

        // MARK: - Generadores y Plataformas AI NSFW / Deepfakes / Roleplay
        "civitai.com", "www.civitai.com",
        "pornpen.ai", "www.pornpen.ai",
        "seduced.ai", "www.seduced.ai",
        "sexyai.com", "www.sexyai.com",
        "promptchan.ai", "www.promptchan.ai",
        "deepnude.cc", "www.deepnude.cc",
        "clothoff.io", "www.clothoff.io",
        "undress.app", "www.undress.app",
        "nudify.online", "www.nudify.online",
        "soulgen.net", "www.soulgen.net",
        "pornx.ai", "www.pornx.ai",
        "fapcam.ai", "www.fapcam.ai",
        "nsfwcharacter.ai", "crushon.ai",
        "janitorai.com", "www.janitorai.com",
        "spicychat.ai", "www.spicychat.ai",
        "candy.ai", "www.candy.ai",
        "moemate.io", "www.moemate.io",
        "chub.ai", "venus.chub.ai",
        
        // MARK: - Hosters de Leaks / OnlyFans Rippers / Archivos NSFW
        "bunkr.is", "www.bunkr.is", "bunkr.su", "bunkr.la", "bunkr.si", "bunkr.ws", "bunkrr.su", "bunkr.cat", "bunkr.ru",
        "cyberdrop.me", "cyberdrop.cc", "cyberdrop.nl",
        "thotslife.com", "www.thotslife.com", "thotsholetv.com", "thothub.to", "thothub.is", "thothub.lol",
        "celebjihad.com", "www.celebjihad.com", "mrskin.com", "www.mrskin.com", "celebzz.com", "aznude.com", "www.aznude.com",
        "vipergirls.to", "www.vipergirls.to", "scanlover.com", "vintage-erotica-forum.com",
        "porntorrents.net", "pornolab.net", "puretna.com", "empornium.sx", "empornium.is",
        
        // MARK: - Citas Adultas, Encuentros & Videochats Aleatorios NSFW
        "pure.app", "www.pure.app",
        "casualx.com", "www.casualx.com",
        "feeld.co", "www.feeld.co",
        "squirt.org", "www.squirt.org",
        "sniffies.com", "www.sniffies.com",
        "scruff.com", "www.scruff.com",
        "recon.com", "www.recon.com",
        "doublelist.com", "www.doublelist.com",
        "chatrandom.com", "www.chatrandom.com",
        "chathub.cam", "www.chathub.cam",
        "dirtyroulette.com", "www.dirtyroulette.com",
        "coomeet.com", "www.coomeet.com",
        "camzap.com", "www.camzap.com",
        "flingster.com", "www.flingster.com",
        "minichat.com", "www.minichat.com",
        
        // MARK: - Sitios Eróticos, Furry, Especializados y Gay / Trans
        "e621.net", "www.e621.net", "e926.net", "www.e926.net",
        "furaffinity.net", "www.furaffinity.net",
        "noodlemagazine.com", "www.noodlemagazine.com",
        "heavyfetish.com", "www.heavyfetish.com",
        "x-art.com", "www.x-art.com",
        "metart.com", "www.metart.com",
        "femjoy.com", "www.femjoy.com",
        "nubiles.net", "www.nubiles.net",
        "hegre.com", "www.hegre.com",
        "alsangels.com", "www.alsangels.com",
        "men.com", "www.men.com",
        "lucasentertainment.com", "www.lucasentertainment.com",
        "seanpass.com", "www.seanpass.com",
        "timtales.com", "www.timtales.com",
        "cockyboys.com", "www.cockyboys.com",
        "helixstudios.com", "www.helixstudios.com",
        "nextdoorstudios.com", "www.nextdoorstudios.com",
        "belamionline.com", "www.belamionline.com",
        "gaytube.com", "www.gaytube.com",
        "pornhubgay.com", "www.pornhubgay.com",
        "maleporn.com", "www.maleporn.com",
        "shemale.xxx", "www.shemale.xxx",
        "tranny.one", "www.tranny.one",
        "grooby.com", "www.grooby.com",

        // MARK: - Foros y Tableros NSFW
        "4chan.org", "boards.4channel.org", "boards.4chan.org", "sys.4chan.org",
        "8kun.top", "www.8kun.top",
        "2ch.hk", "2ch.su",

        // MARK: - Instancias alternativas de Reddit (Libreddit & Redlib - Sin filtros NSFW)
        "libreddit.org", "www.libreddit.org", "libreddit.kavin.rocks", "libreddit.spike.codes",
        "libreddit.northboot.xyz", "libreddit.de", "libreddit.hu", "libreddit.projectsegfau.lt",
        "libreddit.privacydev.net", "libreddit.freedit.eu", "libreddit.mha.fi", "libreddit.oxymagnesium.com",
        "libreddit.tinfoil-hat.net", "libreddit.daveinfinity.com", "libreddit.nohost.network",
        "lr.artemislena.eu", "lr.aeong.one", "reddit.invak.id", "snoo.habedieeh.re", "safereddit.com",
        
        "redlib.catsarch.com", "redlib.perennialte.ch", "redlib.freedit.eu", "redlib.tux.pizza",
        "redlib.ducks.party", "redlib.vslater.top", "redlib.privacydev.net", "redlib.matthew.science",
        "redlib.niruc.com", "redlib.seasi.dev", "redlib.kittywi.re", "redlib.r4fo.com",
        "redlib.tinfoil-hat.net", "redlib.nohost.network", "redlib.drunkencat.net", "redlib.private.coffee",
        "redlib.daik.in", "redlib.402.capital", "redlib.nadeko.net", "redlib.tux.pizza", "redlib.incognet.io",
        "redlib.hbubli.cc", "hbubli.cc",
        
        "teddit.net", "www.teddit.net", "teddit.rawbit.ninja", "teddit.zaggy.nl",
        "teddit.sethforprivacy.com", "teddit.pussthecat.org", "teddit.domain.glass",
        
        // MARK: - Instancias alternativas de Twitter / X (Nitter - Sin filtros)
        "nitter.net", "www.nitter.net", "nitter.cz", "nitter.it", "nitter.privacydev.net",
        "nitter.projectsegfau.lt", "nitter.poast.org", "nitter.woodland.cafe", "nitter.inpt.fr",
        "nitter.eu", "nitter.d420.de", "nitter.moomoo.me", "nitter.x86-64-unknown-linux-gnu.zip",
        "nitter.kavin.rocks", "nitter.1d4.us", "nitter.uni-sonia.com", "nitter.soopy.moe",
        
        // MARK: - Instancias alternativas de TikTok (ProxiTok)
        "proxitok.pabloferreiro.es", "proxitok.pussthecat.org", "tok.habedieeh.re", "proxitok.kavin.rocks"
    ]
    
    /// Patrones heurísticos para detectar instancias presentes y futuras automáticamente
    public static let adultInstanceKeywords: [String] = [
        "terabox", "1024tera", "4funbox", "mirrobox", "nephobox", "freeterabox", "tibibox",
        "terashare", "terafileshare", "teradownload", "teraboxdl", "teraboxdownloader",
        "teradl", "teradrive", "terasaver", "terafast", "teraboxlink", "momerybox", "boxtera",
        "libreddit", "redlib", "teddit", "nitter", "proxitok", "invidious", "piped",
        "coomer.party", "coomer.su", "kemono.party", "kemono.su",
        "fapello", "pornhub", "xvideos", "xnxx", "xhamster",
        "redtube", "youporn", "chaturbate", "stripchat", "erome",
        "pasion.com", "mileroticos", "putalocura", "skokka", "fatalmodel",
        "missav", "hanime", "nhentai", "spankbang",
        "sexmex", "inkasex", "milkyperu", "privaditasperu",
        "bunkr", "cyberdrop", "thothub", "celebjihad", "spicychat", "janitorai", "flingster"
    ]
    
    /// Aplicaciones y navegadores bloqueados automáticamente con el Escudo Anti-Porn
    public static let blockedBrowsers: [BlockedApp] = [
        BlockedApp(bundleIdentifier: "com.duckduckgo.macos.browser", appName: "DuckDuckGo", appPath: "/Applications/DuckDuckGo.app", isEnabled: true),
        BlockedApp(bundleIdentifier: "com.duckduckgo.mobile.ios", appName: "DuckDuckGo Privacy Browser", appPath: "/Applications/DuckDuckGo.app", isEnabled: true),
        BlockedApp(bundleIdentifier: "com.duckduckgo.macos.browser.debug", appName: "DuckDuckGo Debug", appPath: "/Applications/DuckDuckGo.app", isEnabled: true)
    ]
    
    /// Firmas y patrones de TeraBox para detección universal estricta (incluyendo evasiones fonéticas y errores ortográficos)
    public static let teraboxSignatures: [String] = [
        "terabox", "teraboz", "teraboc", "teraz", "terboz", "terbox", "terabx", "teravox",
        "terrabox", "terraboz", "terraboc", "teraboxx", "teraboxs",
        "1024tera", "1024terabox", "1024teraboz", "1024teraz", "1024teraboc",
        "4funbox", "mirrobox", "nephobox", "freeterabox", "tibibox",
        "terashare", "terafileshare", "teradownload", "teraboxdl", "teraboxdownloader",
        "teradl", "teradrive", "terasaver", "terafast", "teraboxlink", "momerybox", "boxtera",
        "terastorage", "teraboxapp", "teraboxurl", "teradrop", "teraboxcdn", "teraboxhls",
        "teraboxvideo", "teraboxdirect", "teraboxplayer", "terastream", "teraboxmp4", "teramp4",
        "teraget", "teraboxbot", "teradown", "flowvideoplayer",
        "tera box", "tera boz", "tera boc", "tera z", "tera vox", "tera bx"
    ]
    
    /// Evalúa si un texto (URL, título, consulta de búsqueda o contenido de página) contiene alguna firma de TeraBox o evasión
    public static func containsTeraBoxSignature(_ text: String) -> Bool {
        guard !text.isEmpty else { return false }
        let lower = text.lowercased()
        
        // 1. Coincidencia directa de firmas en texto bruto
        for sig in teraboxSignatures {
            if lower.contains(sig) {
                return true
            }
        }
        
        // 2. Coincidencia normalizando codificación de URLs (+, %20, espacios adicionales)
        let normalized = lower
            .replacingOccurrences(of: "%20", with: " ")
            .replacingOccurrences(of: "+", with: " ")
        
        for sig in teraboxSignatures {
            if normalized.contains(sig) {
                return true
            }
        }
        
        // 3. Coincidencia de tokens específicos en consultas de búsqueda (ej. q=teraz, q=teraboz)
        if normalized.contains("teraboz") ||
           normalized.contains("teraboc") ||
           normalized.contains("teraz") ||
           normalized.contains("terboz") ||
           normalized.contains("terbox") ||
           normalized.contains("terrabox") ||
           normalized.contains("tera box") ||
           normalized.contains("tera boz") ||
           normalized.contains("tera boc") ||
           normalized.contains("tera z") {
            return true
        }
        
        return false
    }

    /// Palabras clave prohibidas automáticas del escudo Anti-Porn (términos explícitos, pornografía y modelos OnlyFans/adultas de Colombia y Latinoamérica)
    public static let adultKeywords: [String] = [
        // MARK: - TeraBox & Evasiones
        "terabox", "teraboz", "teraboc", "teraz", "terboz", "terbox", "teravox", "terrabox", "terraboz", "terraboc",
        "tera box", "tera boz", "tera boc", "tera z",
        "1024tera", "teraboxapp", "teraboxdownloader", "teraboxdl", "freeterabox",
        "terashare", "terafileshare", "teradownload", "teradl", "teradrive", "terasaver", "terafast",
        "teraboxlink", "tibibox", "4funbox", "mirrobox", "nephobox", "momerybox", "boxtera",
        "terabox video", "terabox mp4", "terabox link", "terabox enlace", "descargar terabox",
        "flowvideoplayer",
        
        // MARK: - Términos Explícitos en Español & Jerga Sexual
        "follando", "follar", "tetas", "teta", "tetonas", "tetona", "culo", "culos", "culona", "culonas",
        "cogiendo", "coger", "chupando", "mamada", "mamadas", "putas", "puta", "prepagos", "prepago",
        "paja", "pajas", "pajeandose", "masturbacion", "masturbandose", "pack", "packs", "squirting", "squirt",
        "anal", "penetracion", "penetrado", "porno casero", "video porno", "videos porno", "fotos porno",
        "onlyfans pack", "onlyfans leaks", "onlyfans filtrado", "leaked pack", "sin censura",
        "desnudos", "desnudo", "desnudas", "desnuda", "encuerada", "encueradas", "encuerado", "encuerados",
        "verga", "polla", "pene", "vagina", "clitoris", "blowjob", "creampie", "cumshot", "deepthroat",
        "threesome", "gangbang", "bukkake", "bdsm", "erotismo", "sexo oral", "sexo anal",
        
        // MARK: - Plataformas, Sitios y Redes para Adultos
        "porn", "porno", "xxx", "sex", "sexx", "hentai", "xvideos", "pornhub", "xhamster",
        "redtube", "onlyfans", "erotic", "erotico", "erotica", "nudity", "nude", "nudes",
        "camgirl", "chaturbate", "escort", "stripper", "fetish", "milf", "rule34", "nsfw",
        "brazzers", "youporn", "xnxx", "redlib", "libreddit", "teddit", "nitter", "proxitok",
        "fapello", "erome", "kemono", "coomer", "spankbang", "missav", "hanime", "nhentai",
        
        // MARK: - 250+ Actrices de Cine para Adultos, Modelos SexMex, Webcam y Creadoras OnlyFans (Colombia, México y Latinoamérica)
        // SexMex (Modelos, Actrices y Producciones)
        "sexmex", "sex mex", "sexmex vip", "sexmexvip", "sexmextv", "modelos sexmex", "actrices sexmex",
        "videos sexmex", "sexmex gratis", "lesly medina", "wendy sanchez", "wendy sánchez", "frida solares",
        "dulce caramelo", "michelle rabbit", "melissa fox", "candy fox", "mia fox", "mía fox",
        "alexa nova", "mariana gomez", "mariana gómez", "pamela rios", "pamela ríos", "samantha saint",
        "brenda trindade", "natasha nice", "lupe fuentes", "penelope kay", "eva karera",
        "rebeca linares", "rebecca linares", "britney rivas", "stacy cruz", "alexa grace",
        "lexi dona", "diana prince", "luna corazon", "luna corazón", "kristal montes", "shantal montes",
        "carolina bellisima", "carolina bellísima", "katana perez", "katana pérez", "paloma jimenez",
        "paloma jiménez", "nicole vega", "miranda miller", "paola canas", "paola cañas",
        "jessica sodi", "dalia fox", "melanie pavola", "maya nazor",
        "kourtney love", "martina smith", "sara blonde", "tatiana alvarez", "tatiana álvarez",
        "salome gil", "salomé gil", "silvana lee", "daniela antury", "valeria fox",
        "claudia bavel", "stephanie cano", "alessandra jane", "monica sanchez", "mónica sánchez",
        "melanie gold", "sophia fiore", "lucia jerez", "lucía jerez", "patricia carter",
        "sabrina banks", "vanessa vargas", "estefania henao", "estefanía henao", "alejandra ospina",
        "diana cuellar", "diana cuéllar", "lorena garcia", "lorena garcía", "camila marin", "camila marín",
        "yorgeis carrillo", "yorgelis carrillo", "jorgeis carrillo", "alisson mayer", "valeria moreno",
        "vanessa angel", "catalina angel", "catalina ángel", "carolina cazadora", "valeria cardona",
        "valentina bella", "sofia cuellar", "sofía cuéllar", "melissa cano", "tatiana gomez", "tatiana gómez",
        "daniella cano", "natalia cano", "valentina riccardi", "karen fischer", "diana melison",
        "estefania rojas", "estefanía rojas", "lorena b", "mariana martinez", "mariana martínez",
        "paola valencia", "jennifer aboul", "dorismar", "wanders lover", "monse swinger",
        "ivonne montero", "monique fuentes", "margarita moreno", "tatiana rosales", "valeria del rio",
        "valeria del río", "alexis amalia", "anabella angel", "carla valencia", "daniella rush",
        "daniela rush", "fabiola martinez", "fabiola martínez", "isabela ramirez", "isabela ramírez",
        "laura angel", "mia diamond", "natalia forest", "roxy panther", "sabrina deep",
        "valeria cross", "vanessa del rio", "vanessa del río", "zuleidy", "zuleidy modelo",
        "naty sanchez", "naty sánchez", "stephanie gomez", "stephanie gómez", "katherine porto",
        "shirley gomez", "shirley gómez", "jessica sanjuan", "jessica sanjuán", "tatiana de los rios",
        "tatiana de los ríos", "karlita banquells", "susana zavaleta", "alicia machado",
        
        // Colombia
        "esperanza gomez", "esperanza gómez", "amaranta hank", "cintia cossio", "andrea valdiri",
        "aida victoria merlano", "luly bossa", "aura cristina geithner", "sandra muñoz", "sandra munoz",
        "yina calderon", "yina calderón", "dani duke", "luisa castro", "jenn muriel",
        "tatiana murillo", "marcela reyes", "manuela gomez", "manuela gómez", "sara uribe",
        "danna sultana", "angie miller", "sharon lopez", "sharon lópez", "katherine martinez",
        "katherine martínez", "carolina abril", "laura gomez", "laura gómez", "catalina cruz",
        "cindy avila", "cindy ávila", "valentina gomez", "valentina gómez", "carla cruz",
        "mia bandini", "sofia nix", "sofía nix", "annie sex teen", "monica santhiago",
        "christie lee", "nicole ferrer", "kelly mancipe", "gina valentina", "la sirena 69",
        "antonella alonso", "maria riot", "elizabeth loaiza", "johana bahamon", "johana bahamón",
        "carolina cruz", "sara corrales", "johanna fadul", "carmen villalobos", "majida issa",
        "lina tejeiro", "greeicy rendon", "greeicy rendón", "jessica cediel", "melina ramirez",
        "melina ramírez", "laura acuña", "laura acuna", "mara cifuentes", "ana karina soto",
        "valerie dominguez", "valerie domínguez", "flavia dos santos", "lady tabares", "natalia duran",
        "natalia durán", "marilyn patiño", "marilyn patino", "kimberly reyes", "juliana velasquez",
        "juliana velásquez", "natalia paris", "natalia parís", "valeria duque", "mafe walker",
        "nanis ochoa", "ana sofia henao", "ana sofía henao",
        
        // México
        "karely ruiz", "celia lora", "yanet garcia", "yanet garcía", "ennid wong",
        "luna bella", "mujer luna bella", "sabrina sabrok", "lizbeth rodriguez", "lizbeth rodríguez",
        "sugey abrego", "sugey ábrego", "ninel conde", "marcela moss", "dulce soltero",
        "mona marisol", "yeri mua", "bellakath", "mia marin", "mía marín",
        "giselle montes", "yamileth ramirez", "yamileth ramírez", "alex marin", "alex marín",
        "brenda zambrano", "manelyk gonzalez", "manelyk gonzález", "dania mendez", "dania méndez",
        "jacky ramirez", "jacky ramírez", "ignacia michelson", "fatima bosch", "fátima bosch",
        "arianny tenorio", "domelipa", "kimberly loaiza", "brianda deyanara", "kenia os",
        "tammy parra", "mont pantoja", "alana flores", "ari gameplays", "arigameplays",
        "rivers gg", "amablitz", "danyan cat", "windygirk",
        
        // Venezuela
        "diosa canales", "jimena araya", "rosita araya", "veronica rodriguez", "verónica rodríguez",
        "juliet lima", "patricia schwarzgruber", "roxana diaz", "roxana díaz", "norkys batista",
        "marjorie de sousa", "wanda d'isidoro", "karen yapoort", "gaby spanic",
        
        // Chile, Argentina, Perú, Brasil y Resto de Latinoamérica
        "daniella chavez", "daniella chávez", "fran undurraga", "adriana barrientos", "cathy barriga",
        "camila polizzi", "faloon larraguibel", "fanny cuevas", "nicole moreno", "gala caldirola",
        "romina malaspina", "florencia peña", "florencia pena", "silvina luna", "wanda nara",
        "cinthia fernandez", "cinthia fernández", "charlotte caniggia", "ivana nadal", "barby silenzi",
        "mica viciconte", "sol perez", "sol pérez", "xoana gonzalez", "xoana gonzález",
        "fatima segovia", "fátima segovia", "deysi araujo", "shirley arica", "leslie shaw",
        "vania bludau", "macarena gastaldo", "rosangela espinoza", "rosángela espinoza", "cindy marino",
        "dorita orbegoso", "andressa urach", "geisy arruda", "suzy cortez", "luiza ambiel",
        "rita cadillac", "morena rial", "cazzu", "maria becerra", "maría becerra",
        "nicki nicole", "tini stoessel", "lali esposito", "lali espósito", "nathy peluso",
        "anitta", "luisa sonza", "luísa sonza", "pabllo vittar", "gracyanne barbosa",
        "juju salimeni", "sabrina sato", "deborah secco", "juliana paes", "cleo pires",
        "raissa barbosa", "mc mirella", "tati zaqui", "kerolay chaves", "martina oliveira",
        "elisa sanches", "tigresa vip", "monica mattos", "mônica mattos", "vivi fernandez",
        "marcia imperator", "ester caroline", "kid bengala", "victoria matosa", "melimtx",
        
        // Estrellas Globales de Cine para Adultos & Top OnlyFans
        "emily willis", "abella danger", "alina lopez", "mia khalifa", "kendra lust",
        "apolonia lapiedra", "silvia saint", "nacho vidal", "amouranth", "bella thorne",
        "bhad bhabie", "corinna kopf", "sommer ray", "lyna perez", "lyna pérez",
        "demi rose", "neiva mara", "belle delphine", "charly jordan", "tana mongeau",
        "larsa pippen", "iggy azalea", "carmen electra", "denise richards", "eva elfie",
        "sweetie fox", "little caprice", "valentina nappi", "lana rhoades", "riley reid",
        "angela white", "nicole aniston", "alexis texas", "tori black", "lisa ann",
        "brandi love", "cory chase", "ava addams", "phoenix marie", "romi rain",
        "cherie deville", "dani daniels", "adriana chechik", "autumn falls", "gabbie carter",
        "violet myers", "lena paul", "maitland ward", "kenzie reeves", "honey gold",
        "liya silver", "jia lissa", "sybil stallone", "tiffany tatum", "tina kay",
        "anny aurora", "amarna miller", "maria lapiedra", "maría lapiedra",
        
        // Búsquedas Frecuentes de Packs, Filtraciones y Canales
        "onlyfans gratis", "ver onlyfans", "filtraciones onlyfans", "packs de famosas",
        "famosas desnudas", "packs mexico", "packs colombia", "packs argentina",
        "packs chile", "packs peru", "telegram packs", "grupos telegram xxx",
        "canales telegram nsfw", "mega pack xxx", "drive xxx", "mediafire xxx",
        "pack de fotos", "pack de videos", "videos filtrados", "pack filtrado",
        "camara oculta xxx", "casero real", "infieles xxx", "pack telegram",
        "pack mega", "links telegram xxx", "fotos intimas", "fotos íntimas",
        "video intimo", "video íntimo", "filtracion intima", "filtración íntima"
    ]
    
    /// Lista exhaustiva de más de 120 motores de búsqueda alternativos y sin moderación estricta
    public static let alternativeSearchEngines: [String] = [
        // DuckDuckGo
        "duckduckgo.com", "www.duckduckgo.com", "safe.duckduckgo.com",
        "html.duckduckgo.com", "lite.duckduckgo.com", "links.duckduckgo.com",
        "duck.com", "www.duck.com",
        // AOL
        "aol.com", "www.aol.com", "search.aol.com", "m.aol.com", "mail.aol.com", "video.aol.com", "aol.es", "aol.co.uk",
        // Search.com & Devilfinder
        "search.com", "www.search.com", "devilfinder.com", "www.devilfinder.com",
        // Disconnect & Privatelee
        "privatelee.com", "www.privatelee.com", "search.disconnect.me", "disconnect.me",
        // People search & Meta
        "spokeo.com", "www.spokeo.com", "freepeoplesearch.com", "www.freepeoplesearch.com",
        "social-searcher.com", "www.social-searcher.com", "base-search.net", "www.base-search.net",
        "kiddle.co", "www.kiddle.co", "yummly.com", "www.yummly.com",
        // Yandex
        "yandex.com", "www.yandex.com", "yandex.ru", "www.yandex.ru", "ya.ru", "yandex.eu", "yandex.by", "yandex.kz", "yandex.uz", "dzen.ru", "yandex.com.tr",
        // Baidu
        "baidu.com", "www.baidu.com", "m.baidu.com", "tieba.baidu.com", "zhidao.baidu.com", "haokan.baidu.com",
        // Brave Search
        "search.brave.com", "api.search.brave.com",
        // Ecosia
        "ecosia.org", "www.ecosia.org",
        // Qwant
        "qwant.com", "www.qwant.com", "api.qwant.com", "lite.qwant.com", "junior.qwant.com",
        // Startpage & Ixquick
        "startpage.com", "www.startpage.com", "startpage.nl", "ixquick.com", "www.ixquick.com", "ixquick.eu", "ixquick.info",
        // Searx & SearXNG instances
        "searx.me", "searx.space", "searx.info", "searxng.org", "searx.be", "searx.ninja", "searx.tiekoetter.com",
        "searx.si", "searx.fmac.xyz", "paulgo.io", "priv.au", "search.sapti.me", "search.bus-hit.me", "search.gcomm.ch",
        "search.onions.eng.br", "searx.work", "northboot.xyz", "search.demoverse.org", "search.mdosch.de",
        "search.charlesreid1.com", "opnxng.com", "search.rowie.at", "searx.dresden.network", "privatesearch.dev",
        "search.im-in.space", "searx.roflcopter.fr", "search.smnz.de", "search.unlocked.link", "searx.ru",
        // Whoogle & LibreX
        "whoogle.io", "whoogle.sdf.org", "whoogle.lunar.icu", "whoogle.catsarch.com", "librex.beparanoid.de", "librex.retrohacker.pro",
        // Swisscows & Mojeek
        "swisscows.com", "www.swisscows.com", "hulbee.com", "mojeek.com", "www.mojeek.com",
        // Kagi, Gibiru, Ask, Dogpile, Lycos, Exalead
        "kagi.com", "www.kagi.com", "ask.com", "www.ask.com", "es.ask.com", "dogpile.com", "www.dogpile.com",
        "lycos.com", "www.lycos.com", "exalead.com", "www.exalead.com", "gibiru.com", "www.gibiru.com",
        // Metasearch & Web Crawlers
        "metacrawler.com", "www.metacrawler.com", "webcrawler.com", "www.webcrawler.com", "gigablast.com", "www.gigablast.com",
        "infospace.com", "www.infospace.com", "peekier.com", "www.peekier.com", "entireweb.com", "www.entireweb.com",
        "teoma.com", "www.teoma.com", "yacy.net", "search.yacy.net", "excite.com", "www.excite.com", "hotbot.com", "www.hotbot.com",
        "alexandria.org", "www.alexandria.org", "marginalia.nu", "search.marginalia.nu", "yep.com", "www.yep.com",
        "stract.com", "www.stract.com", "presearch.com", "www.presearch.com", "presearch.io", "presearch.org",
        "search.disroot.org", "lukol.com", "www.lukol.com", "metager.org", "www.metager.org", "metager.de", "metager.es",
        "oscobo.com", "www.oscobo.com", "andisearch.com", "www.andisearch.com",
        // International Search Engines
        "naver.com", "search.naver.com", "daum.net", "search.daum.net", "goo.ne.jp", "search.goo.ne.jp",
        "sogou.com", "www.sogou.com", "sm.cn", "m.sm.cn", "rambler.ru", "nova.rambler.ru", "go.mail.ru",
        "seznam.cz", "search.seznam.cz", "sapra.io", "egerin.com", "alleba.com", "waldo.fyi", "moonsift.com",
        // Reverse Image & Privacy Search Engines
        "tineye.com", "www.tineye.com", "boardreader.com", "zapmeta.com", "www.zapmeta.com", "zapmeta.ws", "zapmeta.mx",
        "searchencrypt.com", "www.searchencrypt.com", "onesearch.com", "www.onesearch.com", "givero.com", "www.givero.com",
        "ekoru.org", "www.ekoru.org", "oceanhero.today", "www.oceanhero.today", "goodgush.com", "privatesearch.com",
        "searchlock.com", "infinitysearch.co", "findx.com", "feedster.com", "webiator.com", "wiby.me", "millionshort.com",
        "alltheweb.com", "altavista.com", "acoona.com", "cuil.com", "hakia.com", "chacha.com", "mahalo.com", "scour.com",
        "sproose.com", "kartoo.com", "mamma.com", "info.com", "www.info.com", "mywebsearch.com", "search.mywebsearch.com",
        "trova.com", "yippy.com", "kosmix.com", "blinkx.com", "kidrex.org", "jigso.com", "24seek.com", "izito.com",
        "izito.es", "izito.mx", "vinden.nl", "search.ch", "zoeken.nl", "looksmart.com", "webmania.com", "findrequest.com",
        "searchpulse.net", "websearch.com", "searchmine.net", "searchawesome.net", "searchmanager.net", "searchlee.com",
        "searchit.com", "searchsnow.com", "searchmarquis.com", "searchbaron.com", "nearbyme.io"
    ]
}
